development:
  adapter: mysql
  database: test_dev
  username: root
  password: root
  host : 127.0.0.1

test:
  adapter: mysql
  database: test_dev
  username: root
  password: root
  host : 127.0.0.1

production:
  adapter: mysql
  database: prod_test
  username: root
  password: root
  host : 127.0.0.1
